apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Create secret.yaml from secret.example.yaml before apply
resources:
  - ../../base
  - secret.yaml

patches:
  - path: web-nodeport.yaml
